# SPDX-FileCopyrightText: Copyright (c) <2025> NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: inline-samples
        name: Inline samples from templates and kernels regions
        entry: python test/tools/inline_samples.py
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
        files: ^samples/|^test/kernels/|^test/autotuner/autotuner.py
        always_run: false
        require_serial: true
